Feature/read through
T-Tsujii/gyakuten_clone_group33 pull request #30
Opened 2020-10-31 06:44 UTC by evis09

## 今回の実装内容

- 読破ボタンの実装
  - rails g model Likeの実行
  - userとaws_textsを関連ずけ
  - aws_texts/show.html.erbに☆（いいね）を実装

## 参考資料

- 関連付け２
  - https://arcane-gorge-21903.herokuapp.com/texts/297

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）

## 備考
テキスト通りに内容を修正しました。 `model Like`を作成し、指定したuserとaws_textsの関連付けを行いました。（教材ではpostと関連付けられていましたが、viewsにshow.html.erbがあるaws_textsを今回選びました。）このような進め方でよかったでしょうか？

また、☆（いいね）をshowに記述したところ、上手く表示されません。アドバイスを頂きたいです。宜しくお願い致します。

2020-11-07 11:50 UTC, T-Tsujii requested changes
まずは`Like` で作成したものの命名を修正しましょうか。

2020-11-07 11:50 UTC, T-Tsujii commented on config/webpack/environment.js
>  const { environment } = require('@rails/webpacker')
このファイルは元に戻しておいて下さい。

```js
const { environment } = require('@rails/webpacker')

const webpack = require('webpack')
environment.plugins.append('Provide', new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery'
}))

module.exports = environment
```

2020-11-07 11:50 UTC, T-Tsujii commented on db/migrate/20201031052559_create_likes.rb
> +      t.references :user, null: false, foreign_key: true
読破済みですので，`Like` は命名がよろしくないですね。 `read`か `read_text` あたりに変更しましょう。
自分のブランチで作成したファイルですのでロールバック・削除で修正しておきましょうか。

```
rails db:rollback STEP=2
rails d model Like
# db/migrate/20201104130318_rename_aws_texts_id_to_likes.rb を削除
# rails g model コマンドでモデルとテーブルを作成し直す
```

2020-11-11 11:17 UTC, T-Tsujii requested changes

2020-11-11 11:17 UTC, T-Tsujii commented on app/models/movie.rb
> +  end
AWS教材の読破済みを実装するのに動画の方にコードを書いてしまっていますよ。`app/models/aws_text.rb` に移動しましょう。

```suggestion
  validates :title, :url, presence: true
```

2020-11-11 11:17 UTC, T-Tsujii commented on app/models/aws_text.rb
> +  end
```suggestion
  has_many :read_texts, dependent: :destroy
  has_many :read_texted_users, through: :likes, source: :user
  validates :title, :content, presence: true

  def read_text_by?(user)
    read_texts.find_by(user_id: user.id).present?
  end
```

2020-11-11 11:17 UTC, T-Tsujii commented on db/schema.rb
> +  end
テーブルのカラムが正しく生成されていないようです。

```
rails db:rollback
rails db:migrate
```

再度生成しましょう。

エラーが出る場合はロールバックを実行する前に，`db/migrate/20201109080907_create_read_texts.rb`の8行目をコメントアウトし，ロールバック実行後に戻してマイグレーションを行いましょう。

2020-11-11 11:17 UTC, T-Tsujii commented on app/models/read_text.rb
> +            }
`belongs_to` が抜けています。

```suggestion
  belongs_to :user
  belongs_to :aws_text
  validates :user_id, uniqueness: {
              scope: :movie_id,
            }
```

2020-11-11 11:17 UTC, T-Tsujii commented on app/views/movies/index.html.erb
> +    </p>
動画にいいね機能を実装するのでしょうか？AWS教材ではないのでしょうか。

2020-11-11 11:18 UTC, T-Tsujii commented
読破済みボタンをAWS教材に実装するのか動画教材に実装するのかしっかり決めましょう。

2020-11-12 08:29 UTC, evis09 commented on app/views/movies/index.html.erb
> +    </p>
確認してくださりありがとうございます！！教材のように動画の方へふ読破ボタンを設置しようと思います！中途半端な実装失礼致しました。

2020-11-12 08:40 UTC, evis09 commented on db/schema.rb
> +  end
ロールバックは成功しました。しかしマイグレーションを行うと
` PG::UndefinedTable: ERROR:  relation "posts" does not exist `
postsが無いよ！と出てきます。

postカラムが無いということかな？と思い現在のカラムを `rails c `後に `User.column_names`　をして確認してみると確かにありませんでした。追加することで解決するのでしょうか？

しかしpostsなんて使っていませんし、必要無いと思いスルーしています。どのように対応するのが適切でしょうか？

2020-11-12 08:50 UTC, T-Tsujii requested changes

2020-11-12 08:50 UTC, T-Tsujii commented on db/migrate/20201109080907_create_read_texts.rb
> +      t.references :post, null: false, foreign_key: true
ここが `post` が出てくる原因ではありませんか？

```suggestion
      t.references :movie, null: false, foreign_key: true
```

ただ，その前に動画に対して視聴済み機能をつけるならば，命名がread_textsはよろしくないでしょう。
モデル名・テーブル名から修正すべきです。

2020-11-12 09:17 UTC, evis09 commented on db/migrate/20201109080907_create_read_texts.rb
> +      t.references :post, null: false, foreign_key: true
ただ，その前に動画に対して視聴済み機能をつけるならば，命名がread_textsはよろしくないでしょう。
モデル名・テーブル名から修正すべきです。

なるほどです。では特にこだわりも無いので再度修正が必要になるのであれば、aws_textで進めます！２転することお許しください＞＜失礼致しました！！

再度aws_textへ内容を戻し `rails db:migrate`を行いました。ビューへの記述も `aws_texts/show.html.erb`へ変更し記述内容を修正したところ上手く☆マークが表示されました！！続きを進めてみます！ありがとうございます！！

2020-11-13 00:24 UTC, T-Tsujii requested changes

2020-11-13 00:24 UTC, T-Tsujii commented on app/views/aws_texts/show.html.erb
> +  <p id="aws_text-<%= @aws_text_id %>">
ここのidの部分をブラウザで確認して下さい。適切に修正できれば実装に成功するでしょう。

2020-11-13 09:36 UTC, evis09 commented on app/views/aws_texts/_disread_text.html.erb
> +<%= link_to "読破済みにする", aws_text_read_texts_path(aws_text), method: :aws_text, remote: true %>
あ、メソッドもaws_textにしてしまっていたのですね。。ありがとうございます！！

2020-11-15 10:41 UTC, T-Tsujii approved these changes
LGTMです！

2020-11-15 10:41 UTC, merged